projects:
  miNotesApi:
    schemaPath: src/graphql/schema.json
    includes:
      - queries.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
